const prefixes = [
  'Shiny',
  'Dark',
  'Light',
  'Ancient',
  'Mega',
  'Primal',
  'Shadow',
  'Lord',
  'Lady',
  'Mystical',
  'Gemini',
  'Alpha',
  'Omega',
  'Delta',
  'Cosmic',
  'Eternal',
  'Golden',
  'Silver',
  'Crystal',
  'Supreme',
  'Noble',
  'Legendary',
  'Mythical',
  'Heroic',
  'Ace',
  'Elite',
  'Champion',
  'Hidden',
  'Secret',
  'Wild',
  'Raging',
  'Calm',
  'Mighty',
  'Tiny',
  'Giant',
  'Epic',
  'Classic',
];

const mainWords1 = [
  'Pikachu',
  'Charizard',
  'Mewtwo',
  'Lucario',
  'Gengar',
  'Eevee',
  'Dragonite',
  'Garchomp',
  'Rayquaza',
  'Greninja',
  'Meowstic',
  'Kadabra',
  'Happiny',
  'Gardevoir',
  'Snorlax',
  'Arcanine',
  'Bulbasaur',
  'Squirtle',
  'Charmander',
  'Ditto',
  'Mew',
  'Celebi',
  'Jirachi',
  'Zoroark',
  'Kanto',
  'Johto',
  'Hoenn',
  'Sinnoh',
  'Unova',
  'Kalos',
  'Alola',
  'Galar',
  'Paldea',
  'Hisui',
  'Pallet',
  'Pewter',
  'Cerulean',
  'Vermilion',
  'Lavender',
  'Celadon',
  'Fuchsia',
  'Saffron',
  'Cinnabar',
  'Viridian',
  'Goldenrod',
  'Ecruteak',
  'Lumiose',
  'Wyndon',
  'Mesagoza',
  'Red',
  'Blue',
  'Leaf',
  'Ethan',
  'Lyra',
  'Kris',
  'Brendan',
  'May',
  'Lucas',
  'Dawn',
  'Hilbert',
  'Hilda',
  'Nate',
  'Rosa',
  'Calem',
  'Serena',
  'Sun',
  'Moon',
  'Elio',
  'Selene',
  'Victor',
  'Gloria',
  'Florian',
  'Juliana',
  'Cynthia',
  'Steven',
  'Lance',
  'Alder',
  'Diantha',
  'Leon',
  'Nemona',
  'Ash',
  'Brock',
  'Misty',
  'Potion',
  'Revive',
  'Leftovers',
  'Eviolite',
  'Thunderbolt',
  'Flamethrower',
  'Surf',
  'Earthquake',
  'Psychic',
  'Waterfall',
  'Fly',
  'Intimidate',
  'Levitate',
  'Sturdy',
  'Pressure',
  'Static',
  'Guts',
  'Overgrow',
  'Blaze',
  'Torrent',
  'Adaptability',
  'Moxie',
  'Multiscale',
  'Fire',
  'Water',
  'Grass',
  'Electric',
  'Ice',
  'Dragon',
  'Dark',
  'Fairy',
  'Fighting',
  'Flying',
  'Poison',
  'Ground',
  'Rock',
  'Bug',
  'Ghost',
  'Steel',
  'Normal',
];

const mainWords2Plus = [
  'Poke Ball',
  'Great Ball',
  'Ultra Ball',
  'Master Ball',
  'Rare Candy',
  'Life Orb',
  'Choice Scarf',
  'Focus Sash',
  'Amulet Coin',
  'Rocky Helmet',
  'Ice Beam',
  'Rock Slide',
  'Shadow Ball',
  'Close Combat',
  'Dragon Pulse',
  'Hydro Pump',
  'Solar Beam',
  'Hyper Beam',
  'Speed Boost',
];

const suffixes = [
  'Lover',
  'Fan',
  'Master',
  'Specialist',
  'Trainer',
  'Researcher',
  'Collector',
  'Ranger',
  'Seeker',
  'King',
  'Queen',
  'Legend',
  'Expert',
  'Professor',
  'Maniac',
  'Hiker',
  'Leader',
  'Captain',
  'Slayer',
  'Buster',
  'Watcher',
  'Warrior',
  'Sage',
];

const getRandom = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];

export const useNameGenerator = () => {
  const generateName = () => {
    const structure = Math.floor(Math.random() * 4); // 0: Word, 1: Prefix + Word, 2: Word + Suffix, 3: Prefix + Word + Suffix
    let result = '';

    const word1 = getRandom(mainWords1);
    const word2 = getRandom(mainWords2Plus);
    const prefix = getRandom(prefixes);
    const suffix = getRandom(suffixes);

    switch (structure) {
      case 0: // Word
        result = Math.random() > 0.3 ? word2 : word1;
        break;
      case 1: // Prefix + Word
        result = `${prefix} ${Math.random() > 0.5 ? word1 : word2}`;
        break;
      case 2: // Word + Suffix
        result = `${Math.random() > 0.5 ? word1 : word2} ${suffix}`;
        break;
      case 3: // Prefix + Word + Suffix
        result = `${prefix} ${word1} ${suffix}`;
        break;
    }

    return result.slice(0, 50);
  };

  return {
    generateName,
  };
};
